config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: "about"
  get "search" => "searches#search"

  resources :users, only: [:show, :index, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end

  resources :books, only: [:create, :show, :index, :edit, :update, :destroy] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :groups, only: [:new, :create, :show, :index, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
    resources :event_notices, only: [:new, :create]
    get "event_notices" => "event_notices#sent", as: "sent"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search_for(content, method)
    if method == "perfect"
     Book.where(title: content)
    elsif method == "forward"
      Book.wherer("title LIKE?", content + "%")
    elsif method == "backward"
      Book.where("title LIKE?", "%" + content)
    else
      Book.where("title LIKE?", "%" + content + "%")
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :user_id, uniqueness: { scope: :book_id }
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  belongs_to :owner, class_name: "User"
  has_many :users, through: :group_users, source: :user

  validates :name, presence: true
  validates :introduction, presence: true

  has_one_attached :group_image

  def get_group_image
    (group_image.attached?)? group_image: "no_image.jpg"
  end

  def is_owned_by?(user)
    owner_id == user.id
  end

  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :group_users, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :followed_id, dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_one_attached :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    (profile_image.attached? )? profile_image: "no_image.jpg"
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
    if method == "perfect"
     User.where(name: content)
    elsif method == "forward"
      User.wherer("name LIKE?", content + "%")
    elsif method == "backward"
      User.where("name LIKE?", "%" + content)
    else
      User.where("name LIKE?", "%" + content + "%")
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    unless @user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
    @book = Book.new
    @user = User.find(current_user.id)
  end

  def index
    @groups = Group.all
    @book = Book.new
    @user = User.find(current_user.id)
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :group_image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_matching_login_user, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/event_notices_helper.rb
module EventNoticesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model: book do |f| %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control title" %><br>
  </div>

  <div class="form-group">
    <%= f.label :opinion %><br>
    <%= f.text_area :body, class: "form-control body" %>
  </div>

  <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success" %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user) do %>
            <%= image_tag book.user.get_profile_image, size: "80x80" %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
        <td class=<%= "favorite-" + book.id.to_s %>><%= render "favorites/btn", book: book %></td>
        <td class="book-comments-counter"><%= render "book_comments/counter", book: book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
      <%= render "layouts/errors", obj: @book %>

      <%= form_with model: @book, url: book_path(@book), method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
      <% end %>

      <%= link_to "Show", book_path(@book) %> |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render "layouts/errors", obj: @book %>
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "users/info", user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render "books/form", book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render "books/index", books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <%= render "layouts/errors", obj: @book %>
  <div class="row px-5 px-sm-0">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "users/info", user: @book.user %>

      <h2 class="mt-3">New book</h2>
      <%= render "books/form", book: @book_new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>

      <table class="table table-hover table-inverse">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user) do %>
                <%= image_tag @book.user.get_profile_image, size: "80x80" %><br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td><%= link_to @book.title, book_path(@book) %></td>
            <td><%= @book.body %></td>
            <td class=<%= "favorite-" + @book.id.to_s %>><%= render "favorites/btn", book: @book %></td>
            <td class="book-comments-counter"><%= render "book_comments/counter", book: @book %></td>
            <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "btn btn-sm btn-danger" %></td>
            <% end %>
          </tr>
        </thead>
      </table>
      <div class="book-comments-index">
        <%= render "book_comments/index", book: @book %>
      </div>
      <%= render "book_comments/form", book: @book, book_comment: @book_comment %>
    </div>
  </div>
</div>

app/views/groups/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th>メンバー数</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td><%= image_tag group.get_group_image, size: "80x80" %></td>
        <td><%= link_to group.name, group_path(group) %></td>
        <td><%= group.introduction %></td>
        <td><%= group.group_users.count %></td>
        <td>
          <% if group.is_owned_by?(current_user) %>
            <td><%= link_to "Edit", edit_group_path(group.id), class: "btn btn-sm btn-success" %></td>
          <% elsif group.includesUser?(current_user) %>
            <td><%= link_to "Leave this group", group_group_users_path(group.id), method: :delete, class: "btn btn-sm btn-danger" %></td>
          <% else %>
            <td><%= link_to "Join this group", group_group_users_path(group.id), method: :post, class: "btn btn-sm btn-success" %></td>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Group</h2>

      <%= form_with model: @group, url: group_path, method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :グループ名 %>
          <%= f.text_field :name, class: "form-control group-name" %>
        </div>
        <div class="form-group">
          <%= f.label :紹介文 %>
          <%= f.text_area :introduction, class: "form-control group-introduction" %>
        </div>
        <div class="form-group">
          <%= f.label :グループ画像 %>
          <%= f.file_field :group_image, accept: "image/*", class: "form-control-file group-image" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Group", class: "btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "users/info", user: @user %>
      
      <h2 class="mt-3">New book</h2>
      <%= render "books/form", book: @book %>
    </div>
    
    <div class="col-md-8 offset-md-1">
      <h2>Groups</h2>
      <%= render "groups/index", groups: @groups %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <%= render "layouts/errors", obj: @group %>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Create Group</h2>

      <%= form_with model: @group, url: groups_path, method: :post do |f| %>
        <div class="form-group">
          <%= f.label :グループ名 %>
          <%= f.text_field :name, class: "form-control group-name" %>
        </div>
        <div class="form-group">
          <%= f.label :紹介文 %>
          <%= f.text_area :introduction, class: "form-control group-introduction" %>
        </div>
        <div class="form-group">
          <%= f.label :グループ画像 %>
          <%= f.file_field :group_image, accept: "image/*", class: "form-control-file group-image" %>
        </div>
        <div class="form-group">
          <%= f.submit "Create Group", class: "btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container">
  <%= render "layouts/errors", obj: @book %>
  <div class="row px-5 px-sm-0">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "users/info", user: @user %>

      <h2 class="mt-3">New book</h2>
      <%= render "books/form", book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Group detail</h2>

      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= image_tag @group.get_group_image, size: "80x80" %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% @group.users.each do |user| %>
                <p><%= user.name %></p>
              <% end %>
            </td>
            <% if @group.is_owned_by?(current_user) %>
              <td><%= link_to "Edit", edit_group_path(@group), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to "Notice an Event", new_group_event_notice_path(@group), class: "btn btn-sm btn-info" %></td>
            <% elsif @group.includesUser?(current_user) %>
              <td><%= link_to "Leave this group", group_group_users_path(@group), method: :delete, class: "btn btn-sm btn-danger" %></td>
            <% else %>
              <td><%= link_to "Join this group", group_group_users_path(@group), method: :post, class: "btn btn-sm btn-success" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: "80x80" %></td>
        <td><%= user.name %></td>
        <td><%= render "relationships/btn", user: user %></td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<%= image_tag user.get_profile_image, size: "100x100" %>

<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th><%= link_to user.followings.count, user_followings_path(user) %></th>
    </tr>
    <tr>
      <th>followers</th>
      <th><%= link_to user.followers.count, user_followers_path(user) %></th>
    </tr>
  </tbody>
</table>

<div class="row">
  <% if user != current_user %>
    <%= render "relationships/btn", user: user %>
  <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fa-solid fa-user-gear"></i>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= render "layouts/errors", obj: @user %>

      <%= form_with model: @user, url: user_path(@user), method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control name" %>
        </div>
        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :profile_image, accept: "image/*", class: "form-control-file profile_image" %>
        </div>
        <div class="form-group">
          <%= f.label :introduction %>
          <%= f.text_area :introduction, class: "form-control introduction" %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <%= render "layouts/errors", obj: @book %>
  <div class="row px-5 px-sm-0">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "users/info", user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render "books/form", book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <div>
        <%= link_to "グループを作成する", new_group_path %> |
        <%= link_to "グループ一覧", groups_path %>
      </div>
      <%= render "users/index", users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <%= render "layouts/errors", obj: @book %>
  <div class="row px-5 px-sm-0">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "users/info", user: @user %>

      <h2 class="mt-3">New book</h2>
      <%= render "books/form", book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render "books/index", books: @books %>
    </div>
  </div>
</div>